# Generated by Django 6.0.3 on 2026-06-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_candidate_father_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='total_siblings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='father_full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Father's full name"),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='mother_full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Mother's full name"),
        ),
    ]
