# Generated by Django 6.0.3 on 2026-06-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_candidate_total_siblings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='parent_marital_status',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('WIDOW', 'Widow')], default='MARRIED', max_length=20),
        ),
    ]
