# Generated by Django 6.0.3 on 2026-06-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_candidate_parent_marital_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('PASSPORT', 'Passport'), ('BI', 'BI'), ('NIF', 'NIF'), ('NISS', 'NISS'), ('UTENTE', 'UTENTE'), ('TdR', 'TdR'), ('CC', 'CC'), ('CRIMINAL_RECORD', 'Criminal Record'), ('BIRTH_CERT', 'Birth Certificate'), ('DRIVERS_LICENSE', 'Driver License'), ('OTHER', 'Other')], max_length=50, unique=True)),
                ('require_number', models.BooleanField(default=True)),
                ('require_issue_date', models.BooleanField(default=False)),
                ('require_expiry_date', models.BooleanField(default=False)),
                ('require_file', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Document Type Configuration',
                'verbose_name_plural': 'Document Type Configurations',
            },
        ),
    ]
