# Generated by Django 6.0.3 on 2026-07-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_documenttypeconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='parent_marital_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('WIDOW', 'Widow')], default='MARRIED', max_length=20, null=True),
        ),
    ]
