# Generated by Django 6.0.3 on 2026-07-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_candidate_parent_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='candidate_marital_status',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('WIDOW', 'Widow')], default='SINGLE', max_length=20),
        ),
    ]
