# Generated by Django 6.0.3 on 2026-07-21 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_candidate_candidate_marital_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='candidate_marital_status',
        ),
    ]
